### ISSUE TITLE
Ensure PDF Displays Emojis Correctly

### ISSUE THREAD

**Issue by chidoziemanagwu** [chidoziemanagwu/virtual_nutritionist#9]
Description:

Fix the issue where PDF meal plans display black dots or boxes instead of emojis.
Ensure the PDF generator library (e.g., WeasyPrint or ReportLab) supports emojis by using a compatible font like Noto Color Emoji.

**Comment by belkhoujaons** [comment]
can you assign this to me ?

**Comment by chidoziemanagwu** [comment]
yes sure!!

**Comment by chidoziemanagwu** [comment]
please ensure to outline the exact changes you did so i know how to follow it and approve ASAP

**Comment by belkhoujaons** [comment]
> please ensure to outline the exact changes you did so i know how to follow it and approve ASAP

done, can you check it ?
